# Configuration of the CI pipeline
name: 'Google GKE'
canonical: 'stack-gke-sdurrheimer'
status: 'private'
description: 'Used to deploy an Google Kubernetes Engine cluster with one or more node pools.'
keywords:
  - 'kubernetes'
  - 'gke'
  - 'gcloud'
author: 'sdurrheimer'
image: 'https://raw.githubusercontent.com/sdurrheimer/stack-gke/master/icon.png'
type: 'stack'
technologies:
  - technology: Google Kubernetes Engine
    version: latest
  - technology: Container-Optimized OS
    version: latest
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'

  # Configuration of terraform to setup the infrastructure
  terraform:
    gke:
      path: 'terraform/gke.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/gke.tf'
